config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :testimonials
  end
  
  resources :testimonials
end

app/models/spree/testimonial.rb
class Spree::Testimonial < ActiveRecord::Base
end

app/controllers/spree/admin/testimonials_controller.rb
class Spree::Admin::TestimonialsController < Spree::Admin::ResourceController  
  def index
  end
end

app/controllers/spree/testimonials_controller.rb
class Spree::TestimonialsController < Spree::BaseController
  def index
    @testimonials = Spree::Testimonial.all
  end
end

app/helpers/spree/admin/testimonials_helper.rb
module Spree::Admin::TestimonialsHelper
end

app/helpers/spree/testimonials_helper.rb
module Spree::TestimonialsHelper
end

app/views/spree/admin/testimonials/index.html.erb
<div id="new-testimonial"><%= link_to "+ New Testimonial", new_admin_testimonial_path %></div>
<% @testimonials.each do |t| %>
  <div id="testimonial">
    <%= "\"#{t.quote} - #{t.author_name} | #{t.location}\"" %> |
    <%= link_to "Delete", {:action => :destroy, :id => t.id}, :method => :delete %>
  </div>
  <br />
<% end %>

app/views/spree/admin/testimonials/new.html.erb
<%= form_for :testimonial, :url => admin_testimonials_path do |f| %>
  <%= f.label :quote, 'Testimonial' %><br />
  <%= f.text_area :quote, { :rows => 2 } %><br /><br />
  
  <%= f.label :author, 'Author' %><br />
  <%= f.text_field :author_name %><br /><br />
  
  <%= f.label :location, 'Author Location' %><br />
  <%= f.text_field :location %><br /><br />
  
  <%= f.submit 'Save' %>
<% end %>

app/views/spree/testimonials/index.html.erb
<h1 id="testimonials"><%= t('testimonials.testimonials') %></h1>

<ul id="testimonials-list">
  <% @testimonials.each do |t| %>
  <li >
    <blockquote>
      <%= t.quote %>
    </blockquote>
  
    <p class="author">
      <%= t.author_name + (" | #{t.location}" unless t.location.empty?) %> 
    </p>
  </li>
  <% end %>
</ul>